export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const USER_LOADED = 'USER_LOADED';
export const SUB_USER_LOADED = 'SUB_USER_LOADED';
export const SUBADMIN_AUTH_ERROR = 'SUBADMIN_AUTH_ERROR';
export const SUBADMIN_LOGIN_FAIL = 'SUBADMIN_LOGIN_FAIL';
export const SUBADMIN_LOGOUT = 'SUBADMIN_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SINGLE_USER_ERROR = 'SINGLE_USER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS_SUBADMIN = 'LOGIN_SUCCESS_SUBADMIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_SUCCESS_ERROR = 'PASSWORD_SUCCESS_ERROR';
export const MY_PROFILE = 'http://mern.app.com/public/';
export const SITE_URL = 'http://mern.app.com';
export const API_URL = 'http://mern.app.com';

export const UPDATE_STATIC_PAGE = 'UPDATE_STATIC_PAGE';
export const UPDATE_STATIC_PAGE_ERROR = 'UPDATE_STATIC_PAGE_ERROR';
export const GET_STATIC_PAGE_LIST = 'GET_STATIC_PAGE_LIST';
export const GET_STATIC_PAGE_LIST_ERROR = 'GET_STATIC_PAGE_LIST_ERROR';
export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR';
export const UPDATE_TOURNAMENT = 'UPDATE_TOURNAMENT';
export const UPDATE_TOURNAMENT_ERROR = 'UPDATE_TOURNAMENT_ERROR';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const DELETE_TOURNAMENT_ERROR = 'DELETE_TOURNAMENT_ERROR';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_CATEGORY_PAGE = 'GET_CATEGORY_PAGE';
export const GET_CATEGORY_PAGE_ERROR = 'GET_CATEGORY_PAGE_ERROR';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const ADD_SUBCATEGORY_ERROR = 'ADD_SUBCATEGORY_ERROR';
export const GET_SUBCATEGORY_LIST = 'GET_SUBCATEGORY_LIST';
export const GET_SUBCATEGORY_LIST_ERROR = 'GET_SUBCATEGORY_LIST_ERROR';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const GET_SUBCATEGORY_ERROR = 'GET_SUBCATEGORY_ERROR';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const DELETE_SUBCATEGORY_ERROR = 'DELETE_SUBCATEGORY_ERROR';
export const GET_SUBCATEGORY_PAGE_ERROR = 'GET_SUBCATEGORY_PAGE_ERROR';
export const GET_SUBCATEGORY_PAGE = 'GET_SUBCATEGORY_PAGE';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION';
export const GET_QUESTIONS_PAGE = 'GET_QUESTIONS_PAGE';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const ADD_QUESTIONS_ERROR = 'ADD_QUESTIONS_ERROR';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';
export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTION_ERROR = 'GET_QUESTION_ERROR';

export const ADD_GRADE = 'ADD_GRADE';
export const ADD_GRADE_ERROR = 'ADD_GRADE_ERROR';
export const GET_GRADE_LIST = 'GET_GRADE_LIST';
export const GET_GRADE_LIST_ERROR = 'GET_GRADE_LIST_ERROR';
export const GET_GRADE = 'GET_GRADE';
export const GET_GRADE_ERROR = 'GET_GRADE_ERROR';
export const DELETE_GRADE = 'DELETE_GRADE';
export const DELETE_GRADE_ERROR = 'DELETE_GRADE_ERROR';
export const GET_GRADE_PAGE_ERROR = 'GET_GRADE_PAGE_ERROR';
export const GET_GRADE_PAGE = 'GET_GRADE_PAGE';


export const GET_TRANSACTIONS_LIST = 'GET_TRANSACTIONS_LIST';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';
export const GET_STATIC_PAGE_DETAIL = 'GET_STATIC_PAGE_DETAIL';
export const GET_STATIC_PAGE_DETAIL_ERROR = 'GET_STATIC_PAGE_DETAIL_ERROR';
export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICE_ERROR = 'GET_INVOICE_ERROR';

export const GET_REFUND_LIST = 'GET_REFUND_LIST';
export const GET_REFUND_ERROR = 'GET_REFUND_ERROR';

export const GET_MATCHING_LIST = 'GET_MATCHING_LIST';
export const GET_MATCHING_ERROR = 'GET_MATCHING_ERROR';
export const CLIENT = 'CLIENT';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_CHANGE_EMAIL = 'FORGOT_PASSWORD_CHANGE_EMAIL';
export const OTP_VERIFIED_SUCCESS = 'OTP_VERIFIED_SUCCESS';
export const DASHBOARD_USERS = 'DASHBOARD_USERS';
export const DASHBOARD_SESSIONS = 'DASHBOARD_SESSIONS';
export const MANAGEMENT_USERSLIST = 'MANAGEMENT_USERSLIST';
export const SINGLE_USER = 'SINGLE_USER';
export const DASHBOARD_TRANSACTIONS = 'DASHBOARD_TRANSACTIONS';
export const DASHBOARD_TRANSACTIONS_ERROR = 'DASHBOARD_TRANSACTIONS_ERROR';
export const SESSIONS_FOR_CALENDER = 'SESSIONS_FOR_CALENDER';
export const SESSIONS_FOR_CALENDER_ERROR = 'SESSIONS_FOR_CALENDER_ERROR';
export const GET_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES';
export const GET_EMAIL_TEMPLATES_ERROR = 'GET_EMAIL_TEMPLATES_ERROR';
export const DROPDOWN_LIST = 'DROPDOWN_LIST';
export const SESSIONS_LIST = 'SESSIONS_LIST';
export const SESSIONS_LIST_ERROR = 'SESSIONS_LIST_ERROR';
export const TAG_ARRAY_CHANGED = 'TAG_ARRAY_CHANGED';
export const TAG_ARRAY_CHANGED_TO_ZERO = 'TAG_ARRAY_CHANGED_TO_ZERO';


export const STUDENT_SIGNUP_SUCCESS = "STUDENT_SIGNUP_SUCCESS";
export const STUDENT_SIGNUP_ERROR = "STUDENT_SIGNUP_ERROR";

export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_ERROR = "RESEND_OTP_ERROR";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";

export const UPDATE_STUDENT_SUCCESS = " UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";

export const RESET_PASSOWRD_SUCCESS = "RESET_PASSOWRD_SUCCESS";
export const RESET_PASSOWRD_ERROR = "RESET_PASSOWRD_ERROR";

export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_ERROR = "CREATE_CLASS_ERROR";
export const TEACHER_NOTIFICATION = "TEACHER_NOTIFICATION";
export const FAKER = "FAKER";
export const ON_OFF = "ON_OFF";
export const TEACH_ON_OFF = "TEACH_ON_OFF";
export const STRIPE_PUBLISHABLE_KEY = '';
export const STRIPE_SECRET_KEY = '';




